In [12]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold, train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

We create K-folds to know avg performance of our model. We use each fold once as test dataset and all other folds are used as train set

In [3]:
# Creating synthetic Data set
X, y = make_classification(
    n_features=10,
    n_samples=1000,
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2,
    random_state=42
)

In [2]:
# Creating 5 folds
kf = KFold(n_splits=5, shuffle=True, random_state=42)

Let's get the Cross validation scores now for different algorithms

### Logistic Regression

In [6]:
score_lr = cross_val_score(LogisticRegression(), X, y, cv = kf)
score_lr

array([0.675, 0.715, 0.72 , 0.645, 0.72 ])

In [7]:
# We will judge performance by the avg score
np.mean(score_lr)

0.6950000000000001

### Decision Tree Classifier

In [8]:
score_dt = cross_val_score(DecisionTreeClassifier(), X, y, cv = kf)
score_dt

array([0.735, 0.815, 0.795, 0.815, 0.825])

In [9]:
# We will judge performance by the avg score
np.mean(score_dt)

0.7969999999999999

### Random Forst

In [17]:
score_rf = cross_val_score(RandomForestClassifier(), X, y, cv = kf)
score_rf

array([0.84, 0.9 , 0.87, 0.88, 0.91])

In [18]:
# We will judge performance by the avg score
np.mean(score_rf)

0.8799999999999999

Basically cross_val_score and cross_validate do the same job but the only difference is,
* cross_val_score = quick result
* cross_validate = full report

If u want train vs test comparison (overfitting check)

You want multiple metrics like:
* accuracy
* precision
* recall

Then use cross_validate over cross_val_score

In [19]:
from sklearn.model_selection import cross_validate

cross_validate(RandomForestClassifier(), X, y, cv = kf, scoring=['roc_auc'] )

{'fit_time': array([0.45493126, 0.43614244, 0.40546966, 0.3917551 , 0.39039183]),
 'score_time': array([0.01421046, 0.01539993, 0.015064  , 0.01300025, 0.01473355]),
 'test_roc_auc': array([0.93320955, 0.95848339, 0.96618647, 0.95958534, 0.96843637])}

If you only use cross_val_score, you might miss:

* overfitting (no train score)
* performance details

* That’s why professionals often prefer cross_validate