In [1]:
import numpy as np

In [11]:
rev = np.array([[23,57,89],[34,1,78]])
rev

array([[23, 57, 89],
       [34,  1, 78]])

In [3]:
rev.shape

(2, 3)

In [4]:
rev.dtype

dtype('int64')

In [5]:
rev.ndim

2

In [8]:
print(rev[1,0])

34


In [12]:
rev

array([[23, 57, 89],
       [34,  1, 78]])

In [26]:
rev[1,1] = 14
rev

array([[ 1, 14, 78],
       [23, 14, 89]])

In [14]:
rev.size

6

In [15]:
rev.itemsize

8

In [28]:
np.sort(rev, axis = None)

array([ 1, 14, 14, 23, 78, 89])

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.arange(10,20,2) # Step

array([10, 12, 14, 16, 18])

In [44]:
np.linspace(1,5,3) # Parts

array([1., 3., 5.])

In [45]:
rev.ravel()

array([ 1, 14, 78, 23, 14, 89])

In [46]:
rev.flatten()

array([ 1, 14, 78, 23, 14, 89])

In [48]:
rev.reshape(3,2)

array([[ 1, 14],
       [78, 23],
       [14, 89]])

In [50]:
rev.reshape(6,1)

array([[ 1],
       [14],
       [78],
       [23],
       [14],
       [89]])

In [56]:
rev

array([[ 1, 14, 78],
       [23, 14, 89]])

In [57]:
np.sum(rev, axis = 0)

array([ 24,  28, 167])

In [58]:
np.sum(rev, axis = 1)

array([ 93, 126])